In [9]:
import h5py
import numpy as np

filename_TCF = '/data01/gkim/senescence/data/230706_TCF/Fibroblast/230520.123758.20230520.001.Group1.A3.S001/230520.123758.20230520.001.Group1.A3.S001.TCF'

data_TCF = h5py.File(filename_TCF,'r')
ri = np.array(data_TCF.get('Data/3D/000000'))
fl = np.array(data_TCF.get('Data/3DFL/CH0/000000'))

[[[13359 13366 13354 ... 13369 13361 13366]
  [13361 13364 13356 ... 13364 13365 13376]
  [13369 13358 13356 ... 13369 13372 13369]
  ...
  [13380 13386 13385 ... 13369 13382 13365]
  [13372 13364 13369 ... 13352 13365 13376]
  [13381 13378 13377 ... 13370 13370 13377]]

 [[13359 13365 13361 ... 13359 13370 13366]
  [13354 13361 13368 ... 13351 13376 13375]
  [13366 13359 13368 ... 13376 13382 13357]
  ...
  [13375 13385 13388 ... 13365 13378 13369]
  [13375 13371 13373 ... 13366 13365 13375]
  [13377 13376 13379 ... 13380 13370 13374]]

 [[13359 13356 13363 ... 13352 13378 13370]
  [13364 13364 13369 ... 13359 13387 13374]
  [13370 13359 13357 ... 13373 13376 13358]
  ...
  [13373 13378 13387 ... 13362 13368 13373]
  [13375 13374 13383 ... 13363 13361 13378]
  [13372 13379 13384 ... 13374 13364 13371]]

 ...

 [[13366 13366 13364 ... 13351 13357 13360]
  [13374 13368 13356 ... 13366 13367 13364]
  [13373 13374 13369 ... 13377 13369 13367]
  ...
  [13377 13381 13381 ... 13367 13370 133