In [14]:
import torch
import math
from torch.utils.data import IterableDataset, DataLoader

class MyIterableDataset(IterableDataset):
    def __init__(self, data):
        self.data = data
    
    def __iter__(self):
        return iter(self.data)

#def worker_init_fn(worker_id):
#    # Set random seed for each worker based on worker_id
#    torch.manual_seed(torch.initial_seed() + worker_id)
def worker_init_fn(worker_id):
    worker_info = torch.utils.data.get_worker_info()
    
    dataset = worker_info.dataset
    worker_id = worker_info.id
    split_size = len(dataset.data) // worker_info.num_workers
    
    dataset.data = dataset.data[worker_id * split_size: (worker_id + 1) * split_size]
    

# Assuming you have some data
data = [1, 2, 3, 4, 5]

# Create an instance of your IterableDataset
dataset = MyIterableDataset(data)

# Create a DataLoader with IterableDataset and specify worker_init_fn
# Here, num_workers is the number of worker processes
dataloader = DataLoader(dataset, batch_size = 1, num_workers = 3, worker_init_fn=worker_init_fn)

# Iterate over the DataLoader
for batch in dataloader:
    print(batch)

tensor([1])
tensor([2])
tensor([3])
